# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: tf_tree.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='tf_tree.proto',
  package='tf_tree',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\rtf_tree.proto\x12\x07tf_tree\"\x99\x01\n\x02TR\x12\x1a\n\x01p\x18\x01 \x01(\x0b\x32\x0f.tf_tree.TR.Pos\x12\x1b\n\x01q\x18\x02 \x01(\x0b\x32\x10.tf_tree.TR.Quat\x1a&\n\x03Pos\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x1a\x32\n\x04Quat\x12\t\n\x01w\x18\x01 \x01(\x01\x12\t\n\x01x\x18\x02 \x01(\x01\x12\t\n\x01y\x18\x03 \x01(\x01\x12\t\n\x01z\x18\x04 \x01(\x01\">\n\x04Node\x12\x0e\n\x06parent\x18\x01 \x01(\t\x12\x17\n\x02tf\x18\x02 \x01(\x0b\x32\x0b.tf_tree.TR\x12\r\n\x05\x63hild\x18\x03 \x03(\t\"i\n\x04Tree\x12%\n\x04node\x18\x01 \x03(\x0b\x32\x17.tf_tree.Tree.NodeEntry\x1a:\n\tNodeEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\x1c\n\x05value\x18\x02 \x01(\x0b\x32\r.tf_tree.Node:\x02\x38\x01\x62\x06proto3'
)




_TR_POS = _descriptor.Descriptor(
  name='Pos',
  full_name='tf_tree.TR.Pos',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='tf_tree.TR.Pos.x', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='tf_tree.TR.Pos.y', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='z', full_name='tf_tree.TR.Pos.z', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=90,
  serialized_end=128,
)

_TR_QUAT = _descriptor.Descriptor(
  name='Quat',
  full_name='tf_tree.TR.Quat',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='w', full_name='tf_tree.TR.Quat.w', index=0,
      number=1, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='x', full_name='tf_tree.TR.Quat.x', index=1,
      number=2, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='tf_tree.TR.Quat.y', index=2,
      number=3, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='z', full_name='tf_tree.TR.Quat.z', index=3,
      number=4, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=130,
  serialized_end=180,
)

_TR = _descriptor.Descriptor(
  name='TR',
  full_name='tf_tree.TR',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='p', full_name='tf_tree.TR.p', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='q', full_name='tf_tree.TR.q', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_TR_POS, _TR_QUAT, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=27,
  serialized_end=180,
)


_NODE = _descriptor.Descriptor(
  name='Node',
  full_name='tf_tree.Node',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='parent', full_name='tf_tree.Node.parent', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='tf', full_name='tf_tree.Node.tf', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='child', full_name='tf_tree.Node.child', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=182,
  serialized_end=244,
)


_TREE_NODEENTRY = _descriptor.Descriptor(
  name='NodeEntry',
  full_name='tf_tree.Tree.NodeEntry',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='tf_tree.Tree.NodeEntry.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='value', full_name='tf_tree.Tree.NodeEntry.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=b'8\001',
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=293,
  serialized_end=351,
)

_TREE = _descriptor.Descriptor(
  name='Tree',
  full_name='tf_tree.Tree',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='node', full_name='tf_tree.Tree.node', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_TREE_NODEENTRY, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=246,
  serialized_end=351,
)

_TR_POS.containing_type = _TR
_TR_QUAT.containing_type = _TR
_TR.fields_by_name['p'].message_type = _TR_POS
_TR.fields_by_name['q'].message_type = _TR_QUAT
_NODE.fields_by_name['tf'].message_type = _TR
_TREE_NODEENTRY.fields_by_name['value'].message_type = _NODE
_TREE_NODEENTRY.containing_type = _TREE
_TREE.fields_by_name['node'].message_type = _TREE_NODEENTRY
DESCRIPTOR.message_types_by_name['TR'] = _TR
DESCRIPTOR.message_types_by_name['Node'] = _NODE
DESCRIPTOR.message_types_by_name['Tree'] = _TREE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

TR = _reflection.GeneratedProtocolMessageType('TR', (_message.Message,), {

  'Pos' : _reflection.GeneratedProtocolMessageType('Pos', (_message.Message,), {
    'DESCRIPTOR' : _TR_POS,
    '__module__' : 'tf_tree_pb2'
    # @@protoc_insertion_point(class_scope:tf_tree.TR.Pos)
    })
  ,

  'Quat' : _reflection.GeneratedProtocolMessageType('Quat', (_message.Message,), {
    'DESCRIPTOR' : _TR_QUAT,
    '__module__' : 'tf_tree_pb2'
    # @@protoc_insertion_point(class_scope:tf_tree.TR.Quat)
    })
  ,
  'DESCRIPTOR' : _TR,
  '__module__' : 'tf_tree_pb2'
  # @@protoc_insertion_point(class_scope:tf_tree.TR)
  })
_sym_db.RegisterMessage(TR)
_sym_db.RegisterMessage(TR.Pos)
_sym_db.RegisterMessage(TR.Quat)

Node = _reflection.GeneratedProtocolMessageType('Node', (_message.Message,), {
  'DESCRIPTOR' : _NODE,
  '__module__' : 'tf_tree_pb2'
  # @@protoc_insertion_point(class_scope:tf_tree.Node)
  })
_sym_db.RegisterMessage(Node)

Tree = _reflection.GeneratedProtocolMessageType('Tree', (_message.Message,), {

  'NodeEntry' : _reflection.GeneratedProtocolMessageType('NodeEntry', (_message.Message,), {
    'DESCRIPTOR' : _TREE_NODEENTRY,
    '__module__' : 'tf_tree_pb2'
    # @@protoc_insertion_point(class_scope:tf_tree.Tree.NodeEntry)
    })
  ,
  'DESCRIPTOR' : _TREE,
  '__module__' : 'tf_tree_pb2'
  # @@protoc_insertion_point(class_scope:tf_tree.Tree)
  })
_sym_db.RegisterMessage(Tree)
_sym_db.RegisterMessage(Tree.NodeEntry)


_TREE_NODEENTRY._options = None
# @@protoc_insertion_point(module_scope)
